src/Web/Controllers/ToDoItemController.cs
using Microsoft.AspNetCore.Mvc;
using ToDoApp.Application.TodoItems.Commands.CreateTodoItem;
using ToDoApp.Application.Common.Exceptions;
using Microsoft.EntityFrameworkCore;
using System;
using ToDoApp.Application.TodoItems.Commands.DeleteToDoItem;
using ToDoApp.Application.TodoItems.Commands.CompleteToDoItem;

namespace ToDoApp.Web.Controllers;

public class ToDoItemController : Controller
{
    private readonly ISender _sender;

    public ToDoItemController(ISender sender)
    {
        _sender = sender;
    }

    [HttpPost]
    public async Task<IActionResult> Create(CreateTodoItemCommand command, CancellationToken cancellationToken)
    {
        try
        {
            await _sender.Send(command, cancellationToken);
            return RedirectToPage("/Index");
        }
        catch (ValidationException ex)
        {
            var errorMessages = ex.Errors.SelectMany(kvp => kvp.Value.Select(v => $"{kvp.Key}: {v}")).ToList();
            TempData["Errors"] = string.Join("<br/>", errorMessages);
            return RedirectToPage("/Index");
        }
    }
    [HttpPost]
    public async Task<IActionResult> Delete(List<int> itemsId)
    {
        if (itemsId == null || !itemsId.Any())
        {
            TempData["Errors"] = "No items selected for deletion.";
            return RedirectToPage("/Index");
        }
        var command = new DeleteTodoItemCommand { ItemIds = itemsId };
        await _sender.Send(command);
        return RedirectToPage("/Index");
    }
    [HttpPost]
    public async Task<IActionResult> Complete(List<int> itemsId)
    {
        if (itemsId == null || !itemsId.Any())
        {
            TempData["Errors"] = "There are no items selected to mark as complete.";
            return RedirectToPage("/Index");
        }
        var command = new CompleteTodoItemCommand { ItemIds = itemsId };
        await _sender.Send(command);
        return RedirectToPage("/Index");
    }
}

src/Web/Pages/Error.cshtml.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ToDoApp.Web.Pages;

[ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
public class ErrorModel : PageModel
{
    private readonly ILogger<ErrorModel> _logger;

    public ErrorModel(ILogger<ErrorModel> logger)
    {
        _logger = logger;
    }

    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

    public void OnGet()
    {
        RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
    }
}

src/Web/Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc.RazorPages;
using ToDoApp.Application.TodoItems.Queries.GetTodoItems;

namespace ToDoApp.Web.Pages
{
    public class IndexModel : PageModel
    {
        private readonly ISender _sender;

        public IEnumerable<TodoItemBriefDto> Todos { get; set; } = Enumerable.Empty<TodoItemBriefDto>();

        public IEnumerable<string> Errors { get; set; } = Enumerable.Empty<string>();

        public IndexModel(ISender sender)
        {
            _sender = sender;

            if (TempData is not null && TempData.TryGetValue("Errors", out var errors))
            {
                if (errors is not null)
                {
                    Errors = (errors as string[])!;
                }
            }
        }

        public async Task OnGetAsync(CancellationToken cancellationToken = default)
        {
            Todos = await _sender.Send(new GetTodoItemsQuery(), cancellationToken);
        }
    }
}

src/Web/Pages/_Layout.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ToDoApp.Web.Pages
{
    public class _LayoutModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

src/Web/Pages/Index.cshtml
@page
@model ToDoApp.Web.Pages.IndexModel
@{
    Layout = "_Layout";
}

@* @if (TempData.Peek("Errors") is not null)
{
    <div class="alert alert-danger" role="alert">
        @TempData["Errors"]
    </div>
} *@
@if (TempData["Errors"] is not null)
{
    <div class="alert alert-danger" role="alert">
        @Html.Raw(TempData["Errors"]);
    </div>
}

<form method="post" asp-controller="ToDoItem" asp-action="Create">
    <fieldset>
        <legend>Add to do</legend>

        <div class="input-group mb-3">
            <input type="text" class="form-control" placeholder="To do title" name="title">
            <input type="hidden" name="listId" value="1" />
            <button class="btn btn-outline-secondary" type="submit">Add</button>
        </div>
    </fieldset>
</form>
    
@if (Model.Todos.Any())
{
    <form method="post" asp-controller="ToDoItem">
        <div class="list-group">
            @foreach (var todo in Model.Todos)
            {
                <label class="list-group-item d-flex gap-3 strijke">
                    <input class="form-check-input flex-shrink-0" type="checkbox" value="@todo.Id" style="font-size: 1.375em;" name="itemsId">
                    <span class="pt-1 form-checked-content">
                        @if (todo.Done)
                        {
                            <s>@todo.Title</s>
                        }
                        else
                        {
                            <span>@todo.Title</span>
                        }
                    </span>
                </label>
            }
        </div>

        <div class="mt-3">
            <input type="submit" asp-controller="ToDoItem" asp-action="Delete" class="btn btn-danger" value="Delete" />
            <input type="submit" asp-controller="ToDoItem"  asp-action="Complete" class="btn btn-primary" value="Complete" />
        </div>
    </form>
}

src/Web/Pages/_Layout.cshtml
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>@ViewData["Title"] - WebApplication</title>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    </head>
    <body>
        <nav class="navbar navbar-inverse navbar-fixed-top">
            <div class="container">
                <div class="navbar-header">
                    <a asp-page="/" class="navbar-brand">WebApplication</a>
                </div>
            </div>
        </nav>

        <div class="container body-content">
            @RenderBody()
            <hr />
            <footer>
                <p>&copy; @DateTime.Now.Year - Leonardo Vučenović</p>
            </footer>
        </div>

        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
        @RenderSection("Scripts", required: false)
    </body>
</html>